language: python

python:
    - "3.5"

install:
    - virtualenv venv
    - source ./venv/bin/activate
    - pip install -r ./travis-ci/requirements.txt

script:
    - coverage run -m nose2

after_success:
    - coveralls