language: python

python:
    - "3.5"

install:
    - pip install -r ./travis-ci/requirements.txt
    - virtualenv venv
    - source ./venv/bin/activate
    - "pip install -r requirements.txt"

script:
    - python ./tests/examples.py